services:
  gateway:
    build: ./http-gateway
    ports:
      - 3000:3000
    volumes:
      - ./http-gateway/src:/usr/src/app/src
    command: pnpm run start:dev
    environment:
      - PORT=3000

  users-microservice:
    build: ./users-microservice
    volumes:
      - ./users-microservice/src:/usr/src/app/src
    command: pnpm run start:dev

  payments-microservice:
    build: ./users-microservice
    volumes:
      - ./payments-microservice/src:/usr/src/app/src
    command: pnpm run start:dev
    depends_on:
      - gateway
      - users-microservice

  nats:
    image: nats
    ports:
      - 4222:4222

  mysql_db:
    image: mysql
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password_123
      - MYSQL_DATABASE=nestjs_db
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser123
      - MYSQL_TCP_PORT=3307
